# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24b4ae7f63c226f3d0e63e3f22e319acc471315b04685de730e5982c7ffb2a93a0a70c09579aa53c2c862aa00f492abe081f1b882c25a6e37ce2ebf985b6733b

test:
  secret_key_base: 89c9a2fce4cee44430bb9f07d9e7f351cfe11fa17d2553ee7577cd785b6ea341c6c409a981e5942399dc4455b10861311ca4faf7ef75414b5f7787a3e58d53e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
